name: preventivi_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # Pacchetti per Firebase
  firebase_core: any
  firebase_auth: any
  intl: ^0.20.1
  pdf: ^3.11.1
  path_provider: ^2.0.14
  printing: ^5.10.0
  js: ^0.6.3

  # Per le richieste HTTP al server
  http: any

  # Syncfusion libraries aggiornate e compatibili
  syncfusion_flutter_pdf: ^24.1.46
  syncfusion_flutter_datagrid: ^24.2.9
  universal_io: ^2.0.5
  universal_html: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Dichiarazione degli asset
  assets:
    - assests\modello_preventivo_template.pdf