name: preventivi_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # Pacchetti per Firebase
  firebase_core: any
  firebase_auth: any
  intl: ^0.18.0
  pdf: ^3.11.1
  path_provider: ^2.0.14
  printing: ^5.10.0

  # Per le richieste HTTP al server
  #http: ^0.15.0
  http: any
  syncfusion_flutter_datagrid: ^27.2.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
