// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCr67_kKFNPa4NkPTXPyDwxqckuzlBHJ0',
    appId: '1:755559667588:web:4e440942cada4a6dc96fd1',
    messagingSenderId: '755559667588',
    projectId: 'sconga-app-251124',
    authDomain: 'sconga-app-251124.firebaseapp.com',
    storageBucket: 'sconga-app-251124.firebasestorage.app',
    measurementId: 'G-EP38DH7958',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8O-totE8VCaLioyz38_l_8-qP8VyvWcI',
    appId: '1:755559667588:android:201e016bc218608bc96fd1',
    messagingSenderId: '755559667588',
    projectId: 'sconga-app-251124',
    storageBucket: 'sconga-app-251124.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQmaprHUPMbihVoRuMgdBq_55UX0qdmec',
    appId: '1:755559667588:ios:e746b36b71616673c96fd1',
    messagingSenderId: '755559667588',
    projectId: 'sconga-app-251124',
    storageBucket: 'sconga-app-251124.firebasestorage.app',
    iosBundleId: 'com.example.preventiviApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQmaprHUPMbihVoRuMgdBq_55UX0qdmec',
    appId: '1:755559667588:ios:e746b36b71616673c96fd1',
    messagingSenderId: '755559667588',
    projectId: 'sconga-app-251124',
    storageBucket: 'sconga-app-251124.firebasestorage.app',
    iosBundleId: 'com.example.preventiviApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCr67_kKFNPa4NkPTXPyDwxqckuzlBHJ0',
    appId: '1:755559667588:web:78847d016ba5b79ac96fd1',
    messagingSenderId: '755559667588',
    projectId: 'sconga-app-251124',
    authDomain: 'sconga-app-251124.firebaseapp.com',
    storageBucket: 'sconga-app-251124.firebasestorage.app',
    measurementId: 'G-RXLN32R90F',
  );
}
